import { Package, Camera, HardDrive, Monitor, Laptop, Cpu, Router, Cable, Printer, Keyboard, Server, CheckCheck, Zap, Headphones, Globe, Boxes, Sparkles, Wrench } from 'lucide-react';

export const categoryNav = [
  { key: "all", icon: Package, bn: "সকল", en: "All" },
  { key: "CCTV", icon: Camera, bn: "সিসিটিভি", en: "CCTV" },
  { key: "DVR/NVR", icon: HardDrive, bn: "DVR/NVR", en: "DVR/NVR" },
  { key: "Monitor", icon: Monitor, bn: "মনিটর", en: "Monitor" },
  { key: "Laptop", icon: Laptop, bn: "ল্যাপটপ", en: "Laptop" },
  { key: "Computer", icon: Cpu, bn: "কম্পিউটার", en: "Computer" },
  { key: "Networking", icon: Router, bn: "নেটওয়ার্কিং", en: "Networking" },
  { key: "Accessories", icon: Cable, bn: "এক্সেসরিজ", en: "Accessories" },
  { key: "Printer", icon: Printer, bn: "প্রিন্টার", en: "Printer" },
  { key: "Keyboard/Mouse", icon: Keyboard, bn: "কীবোর্ড/মাউস", en: "Keyboard/Mouse" },
  { key: "Server", icon: Server, bn: "সার্ভার", en: "Server" },
  { key: "Attendance Device", icon: CheckCheck, bn: "অ্যাটেনডেন্স", en: "Attendance" },
  { key: "Smart Home", icon: Zap, bn: "স্মার্ট হোম", en: "Smart Home" },
  { key: "Audio/Video", icon: Headphones, bn: "অডিও/ভিডিও", en: "Audio/Video" },
  { key: "Storage", icon: HardDrive, bn: "স্টোরেজ", en: "Storage" },
  { key: "Software", icon: Globe, bn: "সফটওয়্যার", en: "Software" },
];

export const translations = {
  bn: {
    tagline: "বাংলাদেশের বিশ্বস্ত IT সলিউশন কোম্পানি",
    heroTitle1: "আপনার নিরাপত্তা",
    heroTitle2: "আমাদের দায়িত্ব",
    heroDesc: "সিসিটিভি ক্যামেরা, অ্যাটেনডেন্স ডিভাইস, নেটওয়ার্কিং ইকুইপমেন্ট — পেশাদার ইনস্টলেশন ও আফটার সেলস সার্ভিস সহ",
    warranty: "ওয়ারেন্টি সাপোর্ট",
    service247: "24/7 সার্ভিস",
    installation: "প্রফেশনাল ইনস্টলেশন",
    trusted: "বিশ্বস্ত ব্র্যান্ড",
    products: "পণ্যসমূহ",
    services: "সেবাসমূহ",
    packages: "প্যাকেজসমূহ",
    searchProducts: "পণ্য খুঁজুন...",
    productsFound: (n: number) => `${n} টি পণ্য পাওয়া গেছে`,
    noProducts: "কোনো পণ্য পাওয়া যায়নি",
    noServices: "কোনো সেবা পাওয়া যায়নি",
    noPackages: "কোনো প্যাকেজ পাওয়া যায়নি",
    order: "এখনই কিনুন",
    orderService: "অর্ডার করুন",
    inStock: "টি স্টকে আছে",
    outOfStock: "স্টক নেই",
    priceFrom: "মূল্য শুরু",
    budget: "বাজেট",
    includes: "এই প্যাকেজে আছে",
    whyChoose: "কেন আমাদের বেছে নেবেন?",
    whyChooseDesc: "আমরা সবচেয়ে ভালো মানের পণ্য ও সেবা প্রদান করি",
    guaranteeTitle: "গ্যারান্টি ও ওয়ারেন্টি",
    guaranteeDesc: "সকল পণ্যে অফিসিয়াল ওয়ারেন্টি",
    supportTitle: "24/7 কাস্টমার সার্ভিস",
    supportDesc: "যেকোনো সময় কল করুন, আমরা আছি",
    deliveryTitle: "দ্রুত ডেলিভারি",
    deliveryDesc: "ঢাকাসহ সারাদেশে ডেলিভারি",
    teamTitle: "অভিজ্ঞ টিম",
    teamDesc: "১০+ বছরের অভিজ্ঞ টেকনিশিয়ান",
    ctaTitle: "কাস্টম IT সলিউশন দরকার?",
    ctaDesc: "CCTV ইনস্টলেশন, নেটওয়ার্ক সেটআপ, সার্ভার কনফিগারেশন — আমরা সব ধরনের IT সেবা প্রদান করি",
    callUs: "কল করুন",
    contact: "যোগাযোগ",
    address: "ঠিকানা",
    footerDesc: "বাংলাদেশের অন্যতম বিশ্বস্ত IT সলিউশন প্রোভাইডার",
    pending: "চলমান",
    in_progress: "কাজ চলছে",
    completed: "সম্পন্ন",
    headline: "🔥 সকল CCTV ক্যামেরায় বিশেষ ছাড় চলছে! সীমিত সময়ের জন্য অফার — এখনই অর্ডার করুন! 🔥",
    allCategories: "সকল ক্যাটাগরি",
    buildPackage: "প্যাকেজ তৈরি করুন",
    viewDetails: "বিস্তারিত দেখুন",
  },
  en: {
    tagline: "Bangladesh's Trusted IT Solution Company",
    heroTitle1: "Your Security",
    heroTitle2: "Our Responsibility",
    heroDesc: "CCTV cameras, attendance devices, networking equipment — delivered with professional installation & after-sales support.",
    warranty: "Warranty Support",
    service247: "24/7 Service",
    installation: "Professional Installation",
    trusted: "Trusted Brand",
    products: "Products",
    services: "Services",
    packages: "Packages",
    searchProducts: "Search products...",
    productsFound: (n: number) => `${n} product${n !== 1 ? "s" : ""} found`,
    noProducts: "No products found",
    noServices: "No services found",
    noPackages: "No packages available",
    order: "Buy Now",
    orderService: "Order Now",
    inStock: "in stock",
    outOfStock: "Out of Stock",
    priceFrom: "Starting from",
    budget: "Budget",
    includes: "Package Includes",
    whyChoose: "Why Choose Us?",
    whyChooseDesc: "We provide the best quality products and services",
    guaranteeTitle: "Guarantee & Warranty",
    guaranteeDesc: "Official warranty on all products",
    supportTitle: "24/7 Customer Service",
    supportDesc: "Call us anytime, we're here",
    deliveryTitle: "Fast Delivery",
    deliveryDesc: "Delivery across Dhaka & nationwide",
    teamTitle: "Expert Team",
    teamDesc: "10+ years experienced technicians",
    ctaTitle: "Need a Custom IT Solution?",
    ctaDesc: "CCTV installation, network setup, server configuration — we provide all types of IT services",
    callUs: "Call Us",
    contact: "Contact",
    address: "Address",
    footerDesc: "One of Bangladesh's most trusted IT solution providers",
    pending: "Upcoming",
    in_progress: "In Progress",
    completed: "Completed",
    headline: "🔥 Special Discount on All CCTV Cameras! Limited Time Offer — Order Now! 🔥",
    allCategories: "All Categories",
    buildPackage: "Build Package",
    viewDetails: "View Details",
  },
};


export const sectionCards = [
  { key: "products" as const, icon: Package, bnLabel: "পণ্যসমূহ", enLabel: "Products", gradient: "from-violet-600 to-indigo-500", bnDesc: "সিসিটিভি, ল্যাপটপ, নেটওয়ার্কিং", enDesc: "CCTV, Laptop, Networking" },
  { key: "services" as const, icon: Wrench, bnLabel: "সেবা প্যাকেজ", enLabel: "Service Package", gradient: "from-emerald-600 to-teal-600", bnDesc: "ইনস্টলেশন ও সাপোর্ট সেবা", enDesc: "Installation & Support" },
  { key: "packages" as const, icon: Boxes, bnLabel: "প্যাকেজসমূহ", enLabel: "Packages", gradient: "from-purple-600 to-pink-600", bnDesc: "রেডি সিকিউরিটি বান্ডল", enDesc: "Ready Security Bundles" },
  { key: "builder" as const, icon: Sparkles, bnLabel: "প্যাকেজ তৈরি", enLabel: "Build Package", gradient: "from-amber-600 to-orange-600", bnDesc: "নিজের প্যাকেজ কাস্টম করুন", enDesc: "Customize Your Own" },
];

export const serviceSubcategories = [
  { key: "all", icon: Wrench, bn: "সকল", en: "All" },
  { key: "CCTV", icon: Camera, bn: "সিসিটিভি", en: "CCTV" },
  { key: "Attendance Device", icon: CheckCheck, bn: "অ্যাটেনডেন্স", en: "Attendance" },
  { key: "Networking", icon: Router, bn: "নেটওয়ার্কিং", en: "Networking" },
  { key: "IT Support", icon: Headphones, bn: "আইটি সাপোর্ট", en: "IT Support" },
  { key: "Installation", icon: Wrench, bn: "ইনস্টলেশন", en: "Installation" },
  { key: "Server", icon: Server, bn: "সার্ভার", en: "Server" },
  { key: "Maintenance", icon: Monitor, bn: "রক্ষণাবেক্ষণ", en: "Maintenance" },
];

